// Generated by Selenium IDE
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

namespace Alura.ByteBank.WebApp.Testes._seleniumIdeTest;

public class SuiteTests : IDisposable {
  public IWebDriver Driver {get; private set;}
  public IDictionary<string, object> Vars {get; private set;}
  public IJavaScriptExecutor Js {get; private set;}
  public SuiteTests()
  {
    Driver = new ChromeDriver();
    Js = (IJavaScriptExecutor)Driver;
    Vars = new Dictionary<string, object>();
  }
  public void Dispose()
  {
    Driver.Quit();
  }
  [Fact]
  public void LoginNoSistema() {
    Driver.Navigate().GoToUrl("https://localhost:44309/");
    Driver.Manage().Window.Size = new System.Drawing.Size(1616, 868);
    Driver.FindElement(By.LinkText("Login")).Click();
    Driver.FindElement(By.Id("Email")).Click();
    Driver.FindElement(By.Id("Email")).SendKeys("andre@email.com");
    Driver.FindElement(By.Id("Senha")).Click();
    Driver.FindElement(By.Id("Senha")).SendKeys("senha01");
    Driver.FindElement(By.Id("btn-logar")).Click();
    Driver.FindElement(By.CssSelector("html")).Click();
    Driver.FindElement(By.CssSelector(".btn")).Click();
    Driver.Close();
  }
}
